-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."answers" add column "answer_interest" integer
--  not null default '0';
